#!/usr/bin/env bash
# bash script that displays information about domains.
# accept 2 arguments.
# 1. domain: string, domain name to audit, mandatory
# 2. subdomain: string, specific subdomain to audit, not mandatory

subdoms=( "www" "lb-01" "web-01" "web-02" )
dom="$1"
sub="$2"

dig_cmd () {
	# function variables
	sub="$2"

	info=$(dig "$sub.$dom" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')
	ip=$(echo "$info" | awk '{print $5}')
	record=$(echo "$info" | awk '{print $4}')

	echo -e "The subdomain $sub is a $record record and points to $ip"
}

if [ $# -eq 1 ]; then
	for subs in "${subdoms[@]}"; do
		dig_cmd "$dom" "$subs"
	done
elif [ $# -eq 2 ]; then
	dig_cmd "$dom" "$sub"
fi
