#!/usr/bin/env bash
# Install NGINX
sudo apt update
sudo apt install -y nginx

# Listen on port 80 only
sudo ufw allow 'Nginx HTTP'

# backup default index
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# give ownership permission to User for website files, to enable editing
sudo chown -R "$USER" /var/www/html/
sudo chown -R "$USER" /var/www

# create new index
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# setting up /redirect_me to a youtube landing page
sudo sed -i '36a rewrite ^/redirect_me https://youtube.com permanent;' /etc/nginx/sites-available/default

# create 404 page
echo -e "Ceci n'est pas une page\n" >> /var/www/html/error_404.html
sed -i '38i\error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# restart nginx
sudo service nginx restart
