#!/usr/bin/env bash
# Installs and sets up haproxy

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update
sudo apt-get -y install haproxy=2.5.\*

# Listen to web_01 and web_02 servers
sudo chown -R "$USER:$USER" /etc/haproxy

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

echo "
listen http
	bind *:80
	server web1 44.200.42.141:80 check
	server web2 34.231.247.224:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
