#!/usr/bin/env bash
# Installs and sets up haproxy

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update
sudo apt-get install haproxy=2.5.\*

sudo chmod u+w /etc/default/haproxy
sudo echo "ENABLED=1" >> /etc/default/haproxy

# Listen to web_01 and web_02 servers
sudo chown -R "$USER" /etc/haproxy
echo "
	listen load_balancer
	bind *:80
	mode http
	balance roundrobin
	option httpclose
	option forwardclose
	server 21435-web-01 44.200.42.141 check
	server 21435-web-02 34.231.247.224 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
