#!/usr/bin/env bash
# Configures nginx to run as nginx user, listening on port 8080

# give user write permissions on the config file
sudo chmod 644 /etc/nginx/nginx.conf

# create user 'nginx' incase the user does not already exist
sudo useradd nginx > /dev/null 2>&1     # output of this is not needed

# replace the line that contains the string 'user'.
sed -i '/user/c\user nginx;' /etc/nginx/nginx.conf

# find and kill any process that maybe on port 8080, to allow reconfiguration
pkill apache2

# Configure ports.
# modify lines which starts with 'listen' and ends with 'default_server'
sudo sed -i '/:/b; /listen.*.default_server;/c\\tlisten 8080 default_server;' /etc/nginx/sites-enabled/default   # ' /:/b; ' excludes a match of ':' character. -> IPv4

sudo sed -i '/listen.*.:.*.default_server.*/c\\tlisten [::]:8080 default_server ipv6only=on;' /etc/nginx/sites-enabled/default   # only the line containg the character ':' -> IPv6

sudo -u nginx service nginx start
